name: CI

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  ci:
    name: Build and test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    # - name: Install vcpkg
    #   run: ./scripts/install-vcpkg.sh

    - name: Install fmt
      run: vcpkg install fmt

    - name: Build and run
      run: ./scripts/build-and-run.sh
