name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.rubocop.yml'

  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install vcpkg
      run: |
        echo "Cloning..."
        git clone https://github.com/microsoft/vcpkg
        cd vcpkg
        git checkout 5568f11
        if [[ $RUNNER_OS == "Linux" || $RUNNER_OS == "macOS" ]]; then
          ./bootstrap-vcpkg.sh
          ./vcpkg --help
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          .\bootstrap-vcpkg.bat
          .\vcpkg.exe --help
        else
          echo "$RUNNER_OS not supported"
          exit 1
        fi

    - name: Search packages
      run: |
        echo "Searching packages..."
        if [[ $RUNNER_OS == "Linux" || $RUNNER_OS == "macOS" ]]; then
          ./vcpkg search fmt
        elif [[ "$RUNNER_OS" == "Windows" ]]; then
          .\vcpkg.exe search fmt
        fi
        echo "--- [DONE] ---"
