name: CI

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4

    - name: Install fmt
      run: |
        "$VCPKG_INSTALLATION_ROOT"/vcpkg install fmt

    - name: Build and run
      run: |
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
        cmake --build build
        ./build/test

