name: CI

on:
  push:
    paths-ignore:
    - '**.md'
  pull_request:
    paths-ignore:
    - '**.md'
  workflow_dispatch:

jobs:
  ci:
    name: Build and test

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg
      shell: bash
      run: ./scripts/install-vcpkg.sh

    - name: Install dependencies
      shell: bash
      run: ./scripts/install-vcpkg-deps.sh

    - name: Build and run
      shell: bash
      run: ./scripts/build-and-run.sh
